baseURL = "https://brandon.acknsyn.com/"
languageCode = "en-us"
title = "Brandon Atkinson"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/gorjusborg\">Brandon Atkinson</a> 2024"
googleAnalytics = ""

# Number of posts per page
Paginate = 5
enableRobotsTXT = true

pygmentsCodefences=true
pygmentsUseClasses=true
pygmentsCodefencesGuessSyntax=true

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

github = "gorjusborg"
email = "brandon.n.atkinson@gmail.com"
linkedin = "brandon-atkinson-5a45a73"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
